### ISSUE TITLE
Uzależnić możliwość wykonania operacji na notatkach od roli użytkownika

### ISSUE THREAD

**Issue by stanczyk-203999** [stanczyk-203999/SimpleNotesApp#16]
Zabezpieczyć wykonanie metod w zależności od roli np.:
tylko właściciel notatki może dodać nowych użytkowników do niej,
przy usuwaniu notatki przez jednego użytkownika wypisywany jest on tylko z listy jej właścicieli,
przy edycji notatki nie można usunąć innych użytkowników z notatki (może to zrobić tylko admin).

Dla wszystkich użytkowników dostępne musi być:
- dodanie notatki

A dla właściciela notatki wyszczególnić można 3 główne operacje:
- edycja notatki
- dodanie nowego właściciela
- usunięcie siebie z listy właścicieli

Admin ma wszystkie dostępne opcje tj wszystkie operacje CRUD na notatkach i użytkownikach

**Comment by piasecki-203965** [comment]
Zabezpieczono metody operujące na notatkach przed nieautoryzowanymi użytkownikami
