### ISSUE TITLE
Dodać ograniczenie not null na kolumnach i w kodzie oraz zweryfikować inne ograniczenia jak np. UNIQUE

### ISSUE THREAD

**Issue by stanczyk-203999** [stanczyk-203999/SimpleNotesApp#17]

**Comment by adach-203844** [comment]
Dodane ograniczenia not null do pól: title, content, createdTime, modifiedTime w Note. Baza danych również zaktualizowana o takie constrainty. Póki co nie dodawałem adnotacji w dto.
